M48
; DRILL file {KiCad 9.0.8-9.0.8~ubuntu25.10.1} date 2026-04-20T15:28:38+0200
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-04-20T15:28:38+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.8-9.0.8~ubuntu25.10.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X66.305Y-57.81
X66.305Y-63.59
T2
X63.0Y-87.0
M30
