M48
; DRILL file {KiCad 9.0.6-9.0.6~ubuntu24.04.1} date 2025-12-14T15:22:30+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-12-14T15:22:30+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6-9.0.6~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X66.305Y-57.81
X66.305Y-63.59
T2
X63.0Y-87.0
M30
